version: "3"

services:
    verba_db:
        image: postgres:9.6
        container_name: verba_db
        environment:
            - "POSTGRES_DB=quotes"
        networks:
            - verba_network
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    verba_back:
        image: verba_back:1.0
        container_name: verba_back
        volumes:
            - data-static:/verba-back/static
        networks:
            - verba_network
        depends_on:
          - verba_db
        env_file: .verba_env
        command: bash -c "/myvenv/bin/python manage.py migrate && /myvenv/bin/python manage.py collectstatic --noinput && /myvenv/bin/gunicorn verba.wsgi -b 0.0.0.0:8000"

    verba_front:
        image: verba_front:1.0
        depends_on:
          - verba_back
        container_name: verba_front
        ports:
            - "9000:9000"
        volumes:
            - data-static:/verba-back/static
        networks:
            - verba_network


networks:
    verba_network:
        driver: bridge

volumes:
    data-static:
        driver: local
    db-data:
        driver: local
