# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20170710_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='wiki_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
