# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_tags'),
        ('quotes', '0004_auto_20170712_1433'),
    ]

    operations = [
    ]
