# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_merge_20170712_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
