# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20170713_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
